// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxtR34MXaRpsTAf78975dIpEaxAW-Ogo0',
    appId: '1:744663773367:web:93142865220861fb439d32',
    messagingSenderId: '744663773367',
    projectId: 'final-project-81900',
    authDomain: 'final-project-81900.firebaseapp.com',
    storageBucket: 'final-project-81900.appspot.com',
    measurementId: 'G-QSD4V3K39E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMKzPSOEJOKvx14PQwt-MJa_Ap6SEJwI',
    appId: '1:744663773367:android:6a09a1b2cc7d96a3439d32',
    messagingSenderId: '744663773367',
    projectId: 'final-project-81900',
    storageBucket: 'final-project-81900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNnwGmdZd9ppYi6RAJrPEt3v_Fp6BoDB8',
    appId: '1:744663773367:ios:90ab5ffc05681453439d32',
    messagingSenderId: '744663773367',
    projectId: 'final-project-81900',
    storageBucket: 'final-project-81900.appspot.com',
    iosClientId: '744663773367-85686237l7cjbu13mrpcldrkt5mttriv.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
